#!/usr/bin/env bash

{
    echo "zend_extension=xdebug.so"
    echo "xdebug.remote_host=${XDEBUG_REMOTE_HOST}"
    echo "xdebug.remote_enable=1"
    echo "xdebug.remote_autostart=1"
    if [ -z "${XDEBUG_REMOTE_LOG}" ]; then
        echo "xdebug.remote_log=${XDEBUG_REMOTE_LOG}"
    fi

} > /etc/php.d/9999-xdebug.ini

exec "$@"
